### ISSUE TITLE
Please consider individual  functional patches

### ISSUE THREAD

**Issue by oskarpearson** [intel/edison-linux#1]
Hi

I'm eagerly reviewing the changes in wip-edison-3.19.5.. :) I'm currently receiving errors trying to compile the branch, but since it's a WIP I guess that's expected.

Could I trouble you to do something though? The current Intel process of having a HUGE patch file that contains all drivers and all architecture changes makes it very difficult to selectively get one piece working and integrated with a later codebase.

If you could split the commit into patches related to the base architecture changes, the power changes, the USB TO Go changes, and so forth, it'd be a lot easier to manage (and get submitted upstream).

Thanks for your consideration (and time doing the changes you are making at all!)

Oskar

**Comment by dennisjobrien** [comment]
We have split the huge patch into more functional pieces.  Thank you for your input.
