### ISSUE TITLE
failed to restart bluetooth driver

### ISSUE THREAD

**Issue by sunxiaohuix** [intel/edison-linux#14]
root@edison:~# systemctl stop bluetoothctl
Failed to stop bluetoothctl.service: Unit bluetoothctl.service not loaded.

root@edison:~# systemctl start bluetoothctl
Failed to start bluetoothctl.service: Unit bluetoothctl.service failed to load: No such file or directory.

root@edison:~# bluetoothctl
[NEW] Controller 00:11:22:33:55:66 edison [default]
[bluetooth]# agent on
Agent registered
[bluetooth]# default-agent
Default agent request successful
[bluetooth]# discoverable on
Failed to set discoverable on: org.bluez.Error.Failed

**Comment by markwattier** [comment]
The commands "systemctl stop bluetoothctl" and "systemctl start bluetoothctl" have the same result in the existing (edison-image with kernel 3.10) system. "bluetoothctl" is not the name of a systemd service.

The following commands work properly:
rfkill unblock bluetooth
systemctl stop bluetooth
systemctl start bluetooth
bluetoothctl
power on
agent on
default-agent
discoverable on

The "power on" command is not needed with the original edison-image, but is needed with the 3.10 kernel built with Yocto core-image-base Fido branch, after running the stop and start commands. This is also true for the Yocto core-image-base Jethro branch, with the 3.19 kernel.

**Comment by sunxiaohuix** [comment]
The result is passed if send command "power on" in bluetoothctl command line.
