### ISSUE TITLE
Wifi issue is related to the new broadcom driver.

### ISSUE THREAD

**Issue by sunxiaohuix** [intel/edison-linux#15]
I tested with 
# ifconfig wlan0 up
# ifconfig wlan0 down
# ifconfig wlan0 up

SIOCSIFFLAGS: Operation not permitted

And with the kernel log:
[  122.208362] wl_android_wifi_on in
[  122.208381] wifi_platform_set_power = 1
[  122.496787] bcmsdh_sdmmc: Failed to enable F1 Err: 0xffffffc2dhdsdio_probe: ChipClkCSR access: err 0 wrote 0x28 read 0x00 (1)
[  122.575153] dhdsdio_probe: ChipClkCSR access: err 0 wrote 0x28 read 0x00 (2)
[  122.645215] dhdsdio_probe: ChipClkCSR access: err 0 wrote 0x28 read 0x00 (3)
[  122.697165] dhd_net_bus_devreset: dhd_bus_devreset: -35
[  122.697203] 
[  122.697203] Retry WIFI ON procedure (1)

**Comment by dennisjobrien** [comment]
The following commit fixes this issue:

commit c2f5a9e55510497f8b243a7ca9ccde9dbd52f052
Author: Mark Wattier mark.wattier@eqware.net
Date:   Tue May 10 14:12:17 2016 -0700

```
mmc: sdhci: Disable regulator during power off

Change sdhci_set_power to correctly call mmc_regulator_set_ocr to
disable the regulator when power is being turned off.
```

Please update the meta-edison-bsp/recipes-kernel/linux/linux-yocto-edison.bb with the above commit # and rebuild.
Please retest and let us know if this fixes the issue for you.

**Comment by sunxiaohuix** [comment]
The issue has been fixed.

**Comment by dennisjobrien** [comment]
Closed this issue.
