### ISSUE TITLE
rt_preempt

### ISSUE THREAD

**Issue by htot** [intel/edison-linux#6]
Although I'm happy so lots of work is being done on a newer kernel for the Edison, I fail to understand why the choice has fallen on 3.19.5?

I thought Yocto kernels are chosen so that a preempt_rt patch exists? And this is not the case for 3.19.5. 4.0.8 would have been a more logical choice in that respect.

Or am I missing something here?

**Comment by andy-shev** [comment]
I think you may comment here you have done a fork which is more or less works fine, in some cases even better than the official stuff, and close the issue.

**Comment by htot** [comment]
@andy-shev you are right. With kernels from your repository https://github.com/andy-shev/linux/tree/eds-acpi preempt-rt patches just apply and work. I'll put it on my list to publish a Yocto recipe that works as an example.
